export { default as APHorizontalSVG } from './ap-horizontal.svg'
export { default as APMarkSVG } from './ap-mark.svg'
export { default as FMEHorizontalSVG } from './fme-horizontal.svg'
export { default as FMEMarkSVG } from './fme-mark.svg'
export { default as FMEStackedSVG } from './fme-stacked.svg'
